name: Generate Sitemap

on:
  push:
    branches: [ main ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Important for accurate 'lastmod' dates [citation:10]

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://restgenmgr.github.io/nigelthomas-portfolio/

    - name: Commit and push the sitemap
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@users.noreply.github.com'
        git add sitemap.xml
        git commit -m "Automatically generate sitemap" || echo "No changes to commit"
        git push
